/**
 * TempApi
 * This is a sample openApi document
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: lampralexandros@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.TempApi);
  }
}(this, function(expect, TempApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new TempApi.AllmoviesApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('AllmoviesApi', function() {
    describe('createallmovies', function() {
      it('should call createallmovies successfully', function(done) {
        //uncomment below and update the code to test createallmovies
        //instance.createallmovies(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteallmovies', function() {
      it('should call deleteallmovies successfully', function(done) {
        //uncomment below and update the code to test deleteallmovies
        //instance.deleteallmovies(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getAllallmovies', function() {
      it('should call getAllallmovies successfully', function(done) {
        //uncomment below and update the code to test getAllallmovies
        //instance.getAllallmovies(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getByParamsallmovies', function() {
      it('should call getByParamsallmovies successfully', function(done) {
        //uncomment below and update the code to test getByParamsallmovies
        //instance.getByParamsallmovies(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getallmovies', function() {
      it('should call getallmovies successfully', function(done) {
        //uncomment below and update the code to test getallmovies
        //instance.getallmovies(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateallmovies', function() {
      it('should call updateallmovies successfully', function(done) {
        //uncomment below and update the code to test updateallmovies
        //instance.updateallmovies(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
