/**
 * TempApi
 * This is a sample openApi document
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: lampralexandros@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.TempApi);
  }
}(this, function(expect, TempApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new TempApi.ShibaimagesApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ShibaimagesApi', function() {
    describe('createshibaimages', function() {
      it('should call createshibaimages successfully', function(done) {
        //uncomment below and update the code to test createshibaimages
        //instance.createshibaimages(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteshibaimages', function() {
      it('should call deleteshibaimages successfully', function(done) {
        //uncomment below and update the code to test deleteshibaimages
        //instance.deleteshibaimages(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getAllshibaimages', function() {
      it('should call getAllshibaimages successfully', function(done) {
        //uncomment below and update the code to test getAllshibaimages
        //instance.getAllshibaimages(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getByParamsshibaimages', function() {
      it('should call getByParamsshibaimages successfully', function(done) {
        //uncomment below and update the code to test getByParamsshibaimages
        //instance.getByParamsshibaimages(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getshibaimages', function() {
      it('should call getshibaimages successfully', function(done) {
        //uncomment below and update the code to test getshibaimages
        //instance.getshibaimages(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateshibaimages', function() {
      it('should call updateshibaimages successfully', function(done) {
        //uncomment below and update the code to test updateshibaimages
        //instance.updateshibaimages(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
